context:
  name: conda-rattler-solver
  version: "0.0.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/conda-incubator/conda-rattler-solver/archive/${{ version }}.tar.gz
  sha256: b983a030495aed46ab7ab01706719f1b7cf12d3995a4d2a6e9e6fc91087e9934

build:
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION="${{ version }}" python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - conda >=25.5.0
    - py-rattler >=0.20.0

tests:
  - python:
      imports:
        - conda_rattler_solver.solver
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - python -m conda create --dry-run --solver=rattler --channel=conda-forge python

about:
  homepage: https://github.com/conda-incubator/conda-rattler-solver
  summary: 'The fast pixi solver, now in conda'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
