context:
  name: conda-rattler-solver
  version: "0.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/conda-incubator/conda-rattler-solver/archive/${{ version }}.tar.gz
  sha256: e5c628ea5f797abcf5d9e0a101f53ef0dd5e25d7a5f4da2b4c77ba51880c94cc

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - conda >=25.3.0
    - py-rattler >=0.12

tests:
  - python:
      imports:
        - conda_rattler_solver.solver
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - python -m conda create --dry-run python --solver=rattler

about:
  homepage: https://github.com/conda-incubator/conda-rattler-solver
  summary: 'The fast pixi solver, now in conda'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
